rtl/pcore3_pkg.sv
rtl/dea8_fp32_v3_pkg.sv
rtl/dea8_pe_2row_v3.sv
rtl/dea8_mxu_2row_v3.sv
rtl/dea8_afifo_v3.sv
rtl/dea8_xbc4_adapter_v3.sv
rtl/dea8_bfifo_v3.sv
rtl/dea8_b_serializer_v3.sv
rtl/dea8_b_loader_v3.sv
rtl/dea8_matrix_v3.sv
rtl/dea8_pair_store_v3.sv
rtl/dea8_deqacc32_v3.sv
tb/tb_v3_ingress.sv
tb/tb_v3_bpath.sv
tb/tb_v3_pair_store.sv
tb/tb_v3_deqacc32.sv
tb/tb_v3_matrix.sv
