pcore_pkg.sv
dea8_tile_link_pkg.sv
pcore_control_pkg.sv
dea8_pcore_output.sv
dea8_kv_tile_sender.sv
dea8_fp32_pkg.sv
DEQACC_3.3ns_lane.sv
DEQACC_3.3ns.sv
dea8_local_a_store.sv
dea8_pe_2row.sv
dea8_mxu_2row.sv
dea8_afifo.sv
dea8_xbc4_adapter.sv
dea8_bfifo.sv
dea8_b_serializer.sv
dea8_b_loader.sv
dea8_matrix.sv
dea8_projection.sv
dea8_attention_scheduler.sv
dea8_attention_matrix.sv
dea8_pair_store.sv
dea8_gu_pair_buffer.sv
dea8_gu_matrix.sv
dea8_gu_scheduler.sv
dea8_gu_a_replay.sv
dea8_qoz_store.sv
dea8_deqacc32.sv
dea8_acc_store.sv
